language: python
python:
- '2.7'
script:
# Verify the quality of the data.
- python scripts/verifier.py
# Generate the docs for deployment.
- python scripts/gendocs.py
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: docs
  on:
    branch: master
